runtime: php55
api_version: 1
threadsafe: true
 
handlers:
 
- url: /(.+\.(ico|jpg|png|gif|svg))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif|svg))$
  application_readable: true
 
- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$
  application_readable: true
 
- url: /nanogallery
  static_dir: nanogallery
  
- url: /images
  static_dir: images
  
- url: /dist
  static_dir: dist  

- url: /styles
  static_dir: styles    

- url: /(.+\.php)$
  script: \1
   
- url: /.*
  static_files: index.html
  upload: index.html

- url: /$
  static_files: index.html
  upload: index.html  